### ISSUE TITLE
Data path still uses ccemu

### ISSUE THREAD

**Issue by Jummit** [Wilma456/CCLite#2]
I think you just missed this; in ubuntu the path is .local/share/love/**_ccemu_**/data.

**Comment by Wilma456** [comment]
I'm using Ubuntu too and I can't reproduce this. Here's my terminal output when running CCLite:
```
CCLite 2.6
Save Directory is /home/User/.local/share/love/CCLite
Starting CraftOS
```
Are you sure that you use the latest Version?

**Comment by Jummit** [comment]
I was using one of the first releases.
